#! /bin/sh
bspc rule -r "*"

# xrandr --output HDMI-1 --left-of DP-1 --output DVI-D-1 --right-of DP-1
# xrandr --output DP-1 --rate 144.00
pgrep -x sxhkd > /dev/null || sxhkd -m 1 &

bspc monitor HDMI-0 -d 1 2
bspc monitor DP-0 -d 3 4 5 6 7 8
bspc monitor DVI-D-0 -d 9 0

bspc config external_rules_command ~/.config/bspwm/external_rules
bspc config border_width         1
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a 1password state=floating

${HOME}/.fehbg
lxpolkit &
#picom &
compton &
xiccd &
greenclip daemon &
numlockx on
flameshot &
dropbox start -i &
${HOME}/.config/polybar/launch.sh
